class Cliente:
    """Essa clase representa uma pessoa"""

    def __init__(self):
        pass
    
    # qualidades
    nome = "jonas"
    sobrenome = "brothers"
    dinheiro = 0.0

    # estado do cliente
    isvestido = True
    iscabelo = True
    isdepe = True
    isesperando = True
    
    # o que o cliente pode fazer 
    def sentar():
        pass
    
    def levantar():
        pass
    
    def esperar():
        pass